# Generated by Django 4.0.3 on 2022-04-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدرها'},
        ),
    ]
